version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Agents\Dockerfile
        ports:
            - "5000:80"
        networks:
            - aspcore-network

networks:
    aspcore-network:
        driver: bridge